#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2023 OKTET Labs Ltd. All rights reserved.
#
# Helper functions for publishing logs from test suite to
# Bublik web application.

#####################################################################
# Get path to publishing script for a given test suite.
# Arguments:
#   Test suite name.
# Globals:
#   TE_TS_RIGSDIR
#   TE_BUBLIK_PROJECT
# Returns:
#   1 on failure, 0 on success.
# Outputs:
#   Writes script path to stdout.
#####################################################################
tsrigs_publish_get() {
    local ts_name="$1"
    local publish_script
    local defs_file

    if [[ -z "${TE_TS_RIGSDIR}" ]] ; then
        echo "TE_TS_RIGSDIR is not set" >&2
        return 1
    fi

    defs_file="${TE_TS_RIGSDIR}/suites/${ts_name}/defs"
    if [[ ! -r "${defs_file}" ]] ; then
        echo "${defs_file} cannot be read" >&2
        return 1
    fi
    source "${defs_file}"

    if [[ -z "${TE_BUBLIK_PROJECT}" ]] ; then
        echo "TE_BUBLIK_PROJECT is not set" >&2
        return 1
    fi

    publish_script="${TE_TS_RIGSDIR}/scripts/publish_logs/prj"
    publish_script="${publish_script}/${TE_BUBLIK_PROJECT}/publish"
    echo "${publish_script}"
}

#####################################################################
# Publish logs from the last testing.
# This function is intended for use in a standalone publishing script
# in test suite.
# Arguments:
#   Test suite name.
#   All the remaining arguments are passed to Bublik project specific
#     publishing script.
# Globals:
#   TE_BASE
#####################################################################
tsrigs_publish_do() {
    local ts_name="$1"
    local pscript

    shift 1
    pscript="$(tsrigs_publish_get "${ts_name}")"
    ${TE_BASE}/scripts/publish_logs --script="${pscript}" "$@"
}
